version: '2'
services:
    doctorlookup-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/DoctorLookup/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=DoctorLookup
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
